export const ProductsPageActionTypes = {
  SET_PRICE_SORT_DIRECTION: 'SET_PRICE_SORT_DIRECTION',
  SET_NAME_SORT_DIRECTION: 'SET_NAME_SORT_DIRECTION',
  SET_PRICE_FILTER: 'SET_PRICE_FILTER',
  SET_QUERY: 'SET_QUERY',
  TOGGLE_CATEGORY: 'TOGGLE_CATEGORY',
  TOGGLE_BRAND: 'TOGGLE_BRAND',
  RESET_FILTERS: 'RESET_FILTERS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_BRANDS: 'SET_BRANDS',
} as const;
