export const promocodes = [
    {
        id: 1,
        code: 'EXCLUSIVE01',
        discount: 10,
        activationsCount: 4,
        maxActivationsCount: 10,
        type: 'ALL',
        categories: [],
        isActive: true,
    },
    {
        id: 2,
        code: 'EXCLUSIVE02',
        discount: 20,
        activationsCount: 0,
        maxActivationsCount: 10,
        type: 'CATEGORY',
        categories: ['mens-shirts', 'motorcycle', 'sports-accessories', 'beauty', 'groceries', 'womens-bags'],
        isActive: true,
    },
    {
        id: 3,
        code: 'EXCLUSIVE03',
        discount: 5,
        activationsCount: 10,
        maxActivationsCount: 100,
        type: 'ALL',
        categories: [],
        isActive: true,
    },
    {
        id: 4,
        code: 'EXCLUSIVE04',
        discount: 10,
        activationsCount: 10,
        maxActivationsCount: 100, 
        type: 'CATEGORY',
        categories: ['home-decoration', 'motorcycle', 'tops', 'womens-bags', 'womens-shoes', 'womens-watches'],
        isActive: true,
    },
    {
        id: 5,
        code: 'EXCLUSIVE05',
        discount: 30,
        activationsCount: 0,
        maxActivationsCount: 7,
        type: 'ALL',
        categories: [],
        isActive: true,
    },
    {
        id: 6,
        code: 'EXCLUSIVE06',
        discount: 50,
        activationsCount: 0,
        maxActivationsCount: 2,
        type: 'CATEGORY',
        categories: ['beauty', 'home-decoration', 'kitchen-accessories', 'smartphones', 'womens-dresses'],
        isActive: true,
    },
    {
        id: 7,
        code: 'EXCLUSIVE07',
        discount: 15,
        activationsCount: 10,
        maxActivationsCount: 0,
        type: 'CATEGORY',
        categories: ['groceries', 'kitchen-accessories', 'tops', 'vehicle', 'womens-shoes', 'womens-watches'],
        isActive: true,
    },
     {
        id: 8,
        code: 'EXCLUSIVE08',
        discount: 20,
        activationsCount: 10,
        maxActivationsCount: 40,
        type: 'CATEGORY',
        categories: ['beauty', 'mens-shirts', 'mens-watches', 'sports-accessories', 'vehicle', 'womens-dresses'],
        isActive: true,
    },

];